Item list/privacy
sixcare/turplanlegger pull request #48
Opened 2023-02-04 11:13 UTC by sixcare

Added:
 - Privacy for ItemList
 - API call for getting all public lists

Removed:
 - Type for ItemList

2023-02-07 15:59 UTC, peseb requested changes
Veldig nice! Bare litt småpirk:d

2023-02-07 15:59 UTC, peseb commented on turplanlegger/database/schema.sql
> +    private boolean DEFAULT TRUE,
Smart!

2023-02-07 15:59 UTC, peseb commented on turplanlegger/models/item_lists.py
> +        Args:
Ingen args, denne trengs ikke?

2023-02-07 15:59 UTC, peseb commented on turplanlegger/models/item_lists.py
> +    def find_public_item_lists() -> '[ItemList]':
Nice! Det blir fort en ekvivalent metode på trips, routes osv også etterhvert? :D

2023-02-13 17:28 UTC, sixcare commented on turplanlegger/models/item_lists.py
> +    def find_public_item_lists() -> '[ItemList]':
Jepp! Men vi må sikkert legge på begrensing på hvor mange den skal hente

2023-02-14 17:17 UTC, peseb approved these changes

2023-02-14 17:35 UTC, merged